services:
  - type: web
    name: roblox-analytics-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PORT
        value: "10000"
    autoDeploy: true

  - type: web
    name: roblox-analytics-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://roblox-scraping.onrender.com
    autoDeploy: true 
