services:
  - type: web
    name: roblox-analytics-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Roblox500$@db.hkgastbktxpqqxbpokmy.supabase.co:5432/postgres
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "*"
      - key: REQUEST_DELAY_SECONDS
        value: 0.2
      - key: SECRET_KEY
        value: your-production-secret-key-here
    autoDeploy: true

  - type: web
    name: roblox-analytics-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://roblox-analytics-backend.onrender.com
    autoDeploy: true 
